go build server.go
go build relay.go
go build volume.go
go build monitor.go
go build heartbeat.go
go build svarmrMdnsWatcher.go
go build mDNSprocessor.go
go build clipboardProcessor.go
go build moduleStarter.go